pub mod acp;
#[cfg(feature = "tauri-runtime")]
pub mod app_update;
pub mod automation;
pub mod backup;
pub mod chat_channel;
pub mod conversations;
pub mod delegation;
pub mod experts;
pub mod feedback;
#[cfg(feature = "tauri-runtime")]
pub mod file_io;
pub mod folder_commands;
pub mod folders;
pub mod git;
pub mod logging;
pub mod mcp;
pub mod model_provider;
pub mod office_tools;
pub mod science;
pub mod skills;
#[cfg(feature = "tauri-runtime")]
pub mod notification;
pub mod pet;
pub mod project_boot;
pub mod question;
#[cfg(feature = "tauri-runtime")]
pub mod remote_proxy;
#[cfg(feature = "tauri-runtime")]
pub mod remote_workspace;
pub mod session_info;
pub mod system_settings;
pub mod terminal;
pub mod version_control;
#[cfg(feature = "tauri-runtime")]
pub mod windows;
pub mod workspace_state;
pub mod image_generation;
pub mod vision_bridge;
pub mod npm_cli;
#[cfg(feature = "tauri-runtime")]
pub mod image_proxy;
pub mod ppt_generation;
#[cfg(feature = "tauri-runtime")]
pub mod summary;
